import { ExecutionMode } from "../interfaces/Session.interface";
import { IBaseMessage, BaseMessageRole } from "./BaseMessage.contract";

/**
 * Type representing extended roles specific to model messages.
 * Extends the base message roles with additional roles for model-specific scenarios.
 */
export type SwarmMessageRole = BaseMessageRole | "resque" | "flush" | "developer";

/**
 * Interface representing a swarm message within the swarm system.
 * Encapsulates a single message exchanged between agents, tools, users, or the system, used extensively in agent workflows (e.g., ClientAgent) for history tracking, completion generation, and event emission.
 * Messages are stored in history (e.g., via IHistory.push), generated by completions (e.g., ICompletion.getCompletion), and emitted via the bus (e.g., IBus.emit), serving as the core data structure for communication and state management.
 * @extends {IBaseMessage}
*/
export interface ISwarmMessage<Payload extends object = object> extends IBaseMessage<SwarmMessageRole> {
  /**
   * The role is inherited from IBaseMessage but typed as SwarmMessageRole.
   * Defines the origin or purpose in the conversation flow:
   * - `"assistant"`: Generated by the model (e.g., getCompletion output, commitAssistantMessage).
   * - `"system"`: System-level notifications (e.g., commitSystemMessage).
   * - `"tool"`: Tool outputs or tool-related messages (e.g., commitToolOutput, resurrection prompts).
   * - `"user"`: User-initiated messages (e.g., commitUserMessage, EXECUTE_FN input).
   * - `"resque"`: Error recovery messages during model resurrection (e.g., _resurrectModel).
   * - `"flush"`: Markers for history resets (e.g., commitFlush).
   * - `"developer"`: Developer-initiated messages.
   */

  /**
   * The name of the agent associated with the message.
   * Links the message to a specific agent instance (e.g., this.params.agentName in ClientAgent), ensuring context within multi-agent swarms.
   * Used consistently in history pushes and bus events (e.g., context.agentName in IBus.emit).
   */
  agentName: string;

  /**
   * The execution mode indicating the source or context of the message.
   * Aligns with ExecutionMode ("user" or "tool") from Session.interface:
   * - `"user"`: Messages from user input or stateless runs (e.g., commitUserMessage, RUN_FN).
   * - `"tool"`: Messages from tool outputs or system actions (e.g., commitToolOutput, _resurrectModel).
   * Drives processing logic, such as validation or tool call handling in ClientAgent.
   */
  mode: ExecutionMode;

  /**
   * Optional payload data attached to the message, providing additional context or metadata.
   * Can be an object of any shape or `null` if no payload is needed; undefined if not present.
   * Example: `{ image_id: <uuid> }` when user send a message
   */
  payload?: Payload | null;
}
